language: node_js
node_js:
- 6
- 8
script:
- npm run build
before_install:
- npm install -g npm@latest
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy.sh
